# Generated by Django 3.0 on 2021-04-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20210412_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='fire',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='health',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='police',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
